Update github-actions-ec2.yml

diff --git a/.github/workflows/github-actions-ec2.yml b/.github/workflows/github-actions-ec2.yml
--- a/.github/workflows/github-actions-ec2.yml
+++ b/.github/workflows/github-actions-ec2.yml
@@ -55,7 +55,6 @@ jobs:
       
       - name: Check if Key Pair exists
         id: keypair-check
-        if: env.INSTANCE_ID != ''
         run: |
           KEY_PAIR_NAME="${{ secrets.KEY_PAIR_NAME }}"
           EXISTING_KEY=$(aws ec2 describe-key-pairs --key-names $KEY_PAIR_NAME --query 'KeyPairs[0].KeyName' --output text || echo "")
@@ -63,8 +62,8 @@ jobs:
             echo "Creating new Key Pair..."
             aws ec2 create-key-pair --key-name $KEY_PAIR_NAME --query 'KeyMaterial' --output text > ${KEY_PAIR_NAME}.pem
             if [ $? -ne 0 ]; then
-                echo "Failed to create Key Pair" >&2
-                exit 1
+              echo "Failed to create Key Pair" >&2
+              exit 1
             fi
             chmod 400 ${KEY_PAIR_NAME}.pem || exit 1
             echo "KEY_PAIR_FILE=${KEY_PAIR_NAME}.pem" >> $GITHUB_ENV
@@ -72,8 +71,10 @@ jobs:
             # Save the private key as a GitHub secret
             echo "Adding private key to GitHub secrets..."
             gh secret set EC2_SSH_KEY < ${KEY_PAIR_NAME}.pem || echo "Failed to add secret"
+          else
+            echo "Key Pair already exists."
           fi
-          echo "KEY_PAIR=${KEY_PAIR_NAME}" >> $GITHUB_ENV
+
 
       # - name: Check if Key Pair exists
       #   id: keypair-check
