Update github-actions-ec2.yml

diff --git a/.github/workflows/github-actions-ec2.yml b/.github/workflows/github-actions-ec2.yml
--- a/.github/workflows/github-actions-ec2.yml
+++ b/.github/workflows/github-actions-ec2.yml
@@ -102,10 +102,10 @@ jobs:
           # set -e  # Exit immediately if a command exits with a non-zero status
 
           # Update the system and install required packages
-          sudo yum update -y && sudo yum upgrade -y
-          # sudo yum install nginx -y
-          sudo amazon-linux-extras install nginx1
-          sudo yum install python3 python3-devel git nginx -y
+          sudo yum update -y && sudo yum upgrade -y || { echo "Failed to update system"; exit 1; }
+          sudo amazon-linux-extras install nginx1 || { echo "Failed to install Nginx"; exit 1; }
+          sudo yum install python3 python3-devel git nginx -y || { echo "Failed to install required packages"; exit 1; }
+          
           sudo yum install python3-pip -y
       
           # # Install necessary Python packages
@@ -130,8 +130,8 @@ jobs:
           # python3 -m venv venv
           # source venv/bin/activate
 
-          # # Update pip to the newest version
-          # pip install --upgrade pip
+          # Update pip to the newest version
+          pip install --upgrade pip
           # (/home/ec2-user/PokeAPI/myenv/bin/python3 -m pip install --upgrade pip)
 
           # Install required package
@@ -158,8 +158,10 @@ jobs:
           # sudo service iptables save
           # sudo systemctl enable iptables
 
+          sudo groupadd nginx
+          sudo usermod -aG nginx ec2-user
+          newgrp nginx
 
-          
           # Create systemd service
           sudo tee /etc/systemd/system/PokeAPI.service > /dev/null <<EOL
           [Unit]
@@ -168,23 +170,18 @@ jobs:
           
           [Service]
           User=ec2-user
-          Group=ec2-user
-          # Group=www-data
+          Group=nginx
           WorkingDirectory=$APP_DIR/flask_app
-          # Environment="PATH=/home/ec2-user/PokeAPI/venv/bin"  # Adjust this to your virtual environment path
-          # ExecStart=/home/ec2-user/.local/bin/gunicorn --workers 3 --bind unix:/home/ec2-user/PokeAPI/PokeAPI.sock flask_app.app:app
-          # ExecStart=/home/ec2-user/.local/bin/gunicorn --workers 3 --bind unix:/home/ec2-user/PokeAPI/PokeAPI.sock flask_app.app:app
-          # ExecStart=/usr/bin/gunicorn --workers 3 --bind unix:$APP_DIR/flask_app/PokeAPI.sock app:app
-          # ExecStart=/usr/bin/gunicorn --workers 3 --bind unix:$APP_DIR/PokeAPI.sock flask_app.app:app
-          # ExecStart=/usr/bin/gunicorn --workers 3 --bind 0.0.0.0:5000 flask_app.app:app
-          # ExecStart=/usr/bin/gunicorn --workers 3 --bind 0.0.0.0:5000 flask_app.app:app
           ExecStart=/home/ec2-user/.local/bin/gunicorn --workers 3 --bind unix:/home/ec2-user/PokeAPI/PokeAPI.sock app:app
-          # ExecStart=/home/ec2-user/PokeAPI/venv/bin/gunicorn --workers 3 --bind unix:/home/ec2-user/PokeAPI/flask_app/PokeAPI.sock app:app
           Restart=always
           
           [Install]
           WantedBy=multi-user.target
           EOL
+
+          sudo chown ec2-user:nginx /home/ec2-user/PokeAPI/PokeAPI.sock
+          sudo chmod 660 /home/ec2-user/PokeAPI/PokeAPI.sock
+
 
           sudo systemctl daemon-reload
           sudo systemctl start PokeAPI || { echo "Failed to start PokeAPI service"; exit 1; }
@@ -248,7 +245,18 @@ jobs:
       
       - name: Wait for the app to start
         run: sleep 15  # Wait for 15 seconds
-        
+
+      
       - name: Test if the app is running
         run: |
-          curl -I http://${{ env.PUBLIC_DNS }} | grep "200 OK" || echo "Failed to connect to the app"
+          APP_URL="http://${{ env.PUBLIC_DNS }}"
+          RESPONSE=$(curl --write-out "%{http_code}\n" --silent --output /dev/null $APP_URL)
+          if [ "$RESPONSE" -eq 200 ]; then
+            echo "PokeAPI is running successfully! Response code: $RESPONSE"
+          else
+            echo "Failed to reach PokeAPI. Response code: $RESPONSE"
+            exit 1  # Fail the job if the app is not running
+          fi
+      # - name: Test if the app is running
+      #   run: |
+      #     curl -I http://${{ env.PUBLIC_DNS }} | grep "200 OK" || echo "Failed to connect to the app"
